version: '3.8'
    
services:
  
  db:
    image: postgres:latest
    container_name: 'db'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "3369"
      POSTGRES_DB: "postgres"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
          
  
  client:
    build:
      context: client/tic-tac-toe
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:4200"
        
        
  server:
    build:
      context: server/TicTacToe
      dockerfile: TicTacToe.API/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - db
      - rabbitmq

  consumer:
    build:
      context: server/TicTacToe
      dockerfile: TicTacToe.BackGroundService/Dockerfile
    ports:
      - "8001:80"
    restart: always
    depends_on:
      - db
      - rabbitmq